import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { Links } from "./components/Links";
import { LogoutIcon } from "./components/LogoutIcon";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex w-full">
        <div className="bg-white w-[20%] h-screen left-0 p-4 flex flex-col justify-between sticky overflow-hidden top-[0px]">
          <Link href="/">
            <Image src="/pics/lapo.png" alt="Lapo"  width={132} height={45}/>
          </Link>
          <div className="flex flex-col gap-4">
            <div className="flex items-center gap-4">
              <Image src="/pics/e.png" alt="Dashboard" width={16} height={16}/>
              <h1 className="text-[#00000080] text-[12px]">Dashboard</h1>
            </div>
            <div className="flex items-center gap-4">
              <h1 className="text-[#00000080] text-[12px] font-[400]">Main Menu</h1>
            </div>
            <Links />
            <LogoutIcon />
          </div>
        </div>
        <div className="bg-blue-50 w-[80%]">
          {children}
        </div>
      </body>
    </html>
  );
}
